name: mongo-sharding

services:
  # Config Server
  configSrv:
    container_name: configSrv
    image: dh-mirror.gitverse.ru/mongo:latest
    command: mongod --configsvr --replSet configReplSet --port 27019 --bind_ip_all
    volumes:
      - config_data:/data/db
    networks:
      - mongo-network

  # Shard 1
  shard1:
    container_name: shard1
    image: dh-mirror.gitverse.ru/mongo:latest
    command: mongod --shardsvr --replSet shard1ReplSet --port 27018 --bind_ip_all
    volumes:
      - shard1_data:/data/db
    networks:
      - mongo-network

  # Shard 2
  shard2:
    container_name: shard2
    image: dh-mirror.gitverse.ru/mongo:latest
    command: mongod --shardsvr --replSet shard2ReplSet --port 27020 --bind_ip_all
    volumes:
      - shard2_data:/data/db
    networks:
      - mongo-network

  # Mongos Router
  mongos:
    container_name: mongos
    image: dh-mirror.gitverse.ru/mongo:latest
    command: mongos --configdb configReplSet/configSrv:27019 --port 27017 --bind_ip_all
    depends_on:
      - configSrv
      - shard1
      - shard2
    ports:
      - "27017:27017"
    networks:
      - mongo-network

  # API Application
  pymongo_api:
    container_name: pymongo_api
    build:
      context: api_app
      dockerfile: Dockerfile
    depends_on:
      - mongos
    ports:
      - "8080:8080"
    environment:
      MONGODB_URL: "mongodb://mongos:27017"
      MONGODB_DATABASE_NAME: "somedb"
    networks:
      - mongo-network

volumes:
  config_data:
  shard1_data:
  shard2_data:

networks:
  mongo-network:
    driver: bridge
