name: sharding-repl-cache

services:
  # Config Servers (replica set)
  configSrv1:
    container_name: configSrv1
    image: dh-mirror.gitverse.ru/mongo:latest
    command: mongod --configsvr --replSet configReplSet --port 27019 --dbpath /data/db
    volumes:
      - configSrv1_data:/data/db

  configSrv2:
    container_name: configSrv2
    image: dh-mirror.gitverse.ru/mongo:latest
    command: mongod --configsvr --replSet configReplSet --port 27019 --dbpath /data/db
    volumes:
      - configSrv2_data:/data/db

  configSrv3:
    container_name: configSrv3
    image: dh-mirror.gitverse.ru/mongo:latest
    command: mongod --configsvr --replSet configReplSet --port 27019 --dbpath /data/db
    volumes:
      - configSrv3_data:/data/db

  # Shard 1 Replica Set (3 ноды)
  shard1-1:
    container_name: shard1-1
    image: dh-mirror.gitverse.ru/mongo:latest
    command: mongod --shardsvr --replSet shard1ReplSet --port 27018 --dbpath /data/db
    volumes:
      - shard1_1_data:/data/db

  shard1-2:
    container_name: shard1-2
    image: dh-mirror.gitverse.ru/mongo:latest
    command: mongod --shardsvr --replSet shard1ReplSet --port 27018 --dbpath /data/db
    volumes:
      - shard1_2_data:/data/db

  shard1-3:
    container_name: shard1-3
    image: dh-mirror.gitverse.ru/mongo:latest
    command: mongod --shardsvr --replSet shard1ReplSet --port 27018 --dbpath /data/db
    volumes:
      - shard1_3_data:/data/db

  # Shard 2 Replica Set (3 ноды)
  shard2-1:
    container_name: shard2-1
    image: dh-mirror.gitverse.ru/mongo:latest
    command: mongod --shardsvr --replSet shard2ReplSet --port 27018 --dbpath /data/db
    volumes:
      - shard2_1_data:/data/db

  shard2-2:
    container_name: shard2-2
    image: dh-mirror.gitverse.ru/mongo:latest
    command: mongod --shardsvr --replSet shard2ReplSet --port 27018 --dbpath /data/db
    volumes:
      - shard2_2_data:/data/db

  shard2-3:
    container_name: shard2-3
    image: dh-mirror.gitverse.ru/mongo:latest
    command: mongod --shardsvr --replSet shard2ReplSet --port 27018 --dbpath /data/db
    volumes:
      - shard2_3_data:/data/db

  # Mongos Router
  mongos:
    container_name: mongos
    image: dh-mirror.gitverse.ru/mongo:latest
    command: mongos --configdb configReplSet/configSrv1:27019,configSrv2:27019,configSrv3:27019 --bind_ip_all --port 27017
    depends_on:
      - configSrv1
      - configSrv2
      - configSrv3
      - shard1-1
      - shard1-2
      - shard1-3
      - shard2-1
      - shard2-2
      - shard2-3
    ports:
      - "27017:27017"

  # Redis Cache
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data

  # Application
  pymongo-api:
    container_name: pymongo-api
    build: 
      context: api_app
      dockerfile: Dockerfile
    depends_on:
      - mongos
      - redis
    ports:
      - "8080:8080"
    environment:
      MONGODB_URL: "mongodb://mongos:27017"
      MONGODB_DATABASE_NAME: "somedb"
      REDIS_URL: "redis://redis:6379"

volumes:
  configSrv1_data:
  configSrv2_data:
  configSrv3_data:
  shard1_1_data:
  shard1_2_data:
  shard1_3_data:
  shard2_1_data:
  shard2_2_data:
  shard2_3_data:
  redis_data:
