name: sharding-repl-cache

services:
  # Config Servers (Replica Set)
  configSrv1:
    container_name: configSrv1
    image: dh-mirror.gitverse.ru/mongo:latest
    command: mongod --configsvr --replSet configReplSet --port 27019 --bind_ip_all
    ports:
      - "27019:27019"
    volumes:
      - config1_data:/data/db
    networks:
      - mongo-network

  configSrv2:
    container_name: configSrv2
    image: dh-mirror.gitverse.ru/mongo:latest
    command: mongod --configsvr --replSet configReplSet --port 27019 --bind_ip_all
    ports:
      - "27020:27019"
    volumes:
      - config2_data:/data/db
    networks:
      - mongo-network

  # Shard 1 - Replica Set 1 (rs1)
  shard1-1:
    container_name: shard1-1
    image: dh-mirror.gitverse.ru/mongo:latest
    command: mongod --shardsvr --replSet rs1 --port 27018 --bind_ip_all
    ports:
      - "27021:27018"
    volumes:
      - shard1_1_data:/data/db
    networks:
      - mongo-network

  shard1-2:
    container_name: shard1-2
    image: dh-mirror.gitverse.ru/mongo:latest
    command: mongod --shardsvr --replSet rs1 --port 27018 --bind_ip_all
    ports:
      - "27022:27018"
    volumes:
      - shard1_2_data:/data/db
    networks:
      - mongo-network

  shard1-3:
    container_name: shard1-3
    image: dh-mirror.gitverse.ru/mongo:latest
    command: mongod --shardsvr --replSet rs1 --port 27018 --bind_ip_all
    ports:
      - "27023:27018"
    volumes:
      - shard1_3_data:/data/db
    networks:
      - mongo-network

  # Shard 2 - Replica Set 2 (rs2)
  shard2-1:
    container_name: shard2-1
    image: dh-mirror.gitverse.ru/mongo:latest
    command: mongod --shardsvr --replSet rs2 --port 27018 --bind_ip_all
    ports:
      - "27024:27018"
    volumes:
      - shard2_1_data:/data/db
    networks:
      - mongo-network

  shard2-2:
    container_name: shard2-2
    image: dh-mirror.gitverse.ru/mongo:latest
    command: mongod --shardsvr --replSet rs2 --port 27018 --bind_ip_all
    ports:
      - "27025:27018"
    volumes:
      - shard2_2_data:/data/db
    networks:
      - mongo-network

  shard2-3:
    container_name: shard2-3
    image: dh-mirror.gitverse.ru/mongo:latest
    command: mongod --shardsvr --replSet rs2 --port 27018 --bind_ip_all
    ports:
      - "27026:27018"
    volumes:
      - shard2_3_data:/data/db
    networks:
      - mongo-network

  # Mongos Router
  mongos:
    container_name: mongos
    image: dh-mirror.gitverse.ru/mongo:latest
    command: mongos --configdb configReplSet/configSrv1:27019,configSrv2:27019 --bind_ip_all --port 27017
    ports:
      - "27017:27017"
    depends_on:
      - configSrv1
      - configSrv2
      - shard1-1
      - shard1-2
      - shard1-3
      - shard2-1
      - shard2-2
      - shard2-3
    networks:
      - mongo-network

  # Redis Cache
  redis:
    container_name: redis
    image: dh-mirror.gitverse.ru/redis:latest
    ports:
      - "6379:6379"
    networks:
      - mongo-network

  # API Application
  pymongo_api:
    container_name: pymongo_api
    build:
      context: api_app
      dockerfile: Dockerfile
    depends_on:
      - mongos
      - redis
    ports:
      - "8080:8080"
    environment:
      MONGODB_URL: "mongodb://mongos:27017"
      MONGODB_DATABASE_NAME: "somedb"
      REDIS_URL: "redis://redis:6379"
    networks:
      - mongo-network

volumes:
  config1_data:
  config2_data:
  shard1_1_data:
  shard1_2_data:
  shard1_3_data:
  shard2_1_data:
  shard2_2_data:
  shard2_3_data:

networks:
  mongo-network:
    driver: bridge
