name: sharding-repl-cache

services:
  pymongo_api:
    container_name: pymongo_api
    build:
      context: api_app
      dockerfile: Dockerfile
    depends_on:
      mongos_router:
        condition: service_healthy
      cluster_init:
        condition: service_completed_successfully
      redis-cluster-init:
        condition: service_completed_successfully
    ports:
      - 8080:8080
    environment:
      MONGODB_URL: "mongodb://mongos_router:27020"
      MONGODB_DATABASE_NAME: "somedb"
      REDIS_URL: "redis://redis-node-1:6379,redis-node-2:6379,redis-node-3:6379,redis-node-4:6379,redis-node-5:6379,redis-node-6:6379"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Конфигурационные серверы
  configSrv1:
    image: mongo:latest
    restart: always
    command: mongod --configsvr --replSet configrs --bind_ip_all --port 27017
    ports:
      - "27017:27017"
    volumes:
      - configSrv1_data:/data/db
      - configSrv1_config:/data/configdb
      - ./scripts:/scripts
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')", "--quiet" ]
      interval: 10s
      timeout: 20s
      retries: 10
      start_period: 60s

  configSrv2:
    image: mongo:latest
    restart: always
    command: mongod --configsvr --replSet configrs --bind_ip_all --port 27017
    ports:
      - "27018:27017"
    volumes:
      - configSrv2_data:/data/db
      - configSrv2_config:/data/configdb
      - ./scripts:/scripts
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')", "--quiet" ]
      interval: 10s
      timeout: 20s
      retries: 10
      start_period: 60s
    depends_on:
      configSrv1:
        condition: service_started

  configSrv3:
    image: mongo:latest
    restart: always
    command: mongod --configsvr --replSet configrs --bind_ip_all --port 27017
    ports:
      - "27019:27017"
    volumes:
      - configSrv3_data:/data/db
      - configSrv3_config:/data/configdb
      - ./scripts:/scripts
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')", "--quiet" ]
      interval: 10s
      timeout: 20s
      retries: 10
      start_period: 60s
    depends_on:
      configSrv1:
        condition: service_started
      configSrv2:
        condition: service_started

  # Инициализатор конфигурационных серверов
  cfg_init:
    image: mongo:latest
    volumes:
      - ./scripts:/scripts
    networks:
      - app-network
    entrypoint: [ "/bin/bash", "/scripts/wait-and-init-cfg.sh" ]
    depends_on:
      configSrv1:
        condition: service_healthy
      configSrv2:
        condition: service_healthy
      configSrv3:
        condition: service_healthy

  # 1-й шард (3 реплики)
  shard1a:
    image: mongo:latest
    restart: always
    command: mongod --shardsvr --replSet shard1rs --bind_ip_all --port 27017
    ports:
      - "27021:27017"
    volumes:
      - shard1a_data:/data/db
      - ./scripts:/scripts
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    depends_on:
      cfg_init:
        condition: service_completed_successfully

  shard1b:
    image: mongo:latest
    restart: always
    command: mongod --shardsvr --replSet shard1rs --bind_ip_all --port 27017
    ports:
      - "27022:27017"
    volumes:
      - shard1b_data:/data/db
      - ./scripts:/scripts
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    depends_on:
      shard1a:
        condition: service_started

  shard1c:
    image: mongo:latest
    restart: always
    command: mongod --shardsvr --replSet shard1rs --bind_ip_all --port 27017
    ports:
      - "27023:27017"
    volumes:
      - shard1c_data:/data/db
      - ./scripts:/scripts
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    depends_on:
      shard1a:
        condition: service_started
      shard1b:
        condition: service_started

  # Инициализатор шарда 1
  shard1_init:
    image: mongo:latest
    volumes:
      - ./scripts:/scripts
    networks:
      - app-network
    entrypoint: [ "/bin/bash", "/scripts/wait-and-init-shard1.sh" ]
    depends_on:
      shard1a:
        condition: service_healthy
      shard1b:
        condition: service_healthy
      shard1c:
        condition: service_healthy

  # 2-й шард (3 реплики)
  shard2a:
    image: mongo:latest
    restart: always
    command: mongod --shardsvr --replSet shard2rs --bind_ip_all --port 27017
    ports:
      - "27024:27017"
    volumes:
      - shard2a_data:/data/db
      - ./scripts:/scripts
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    depends_on:
      cfg_init:
        condition: service_completed_successfully

  shard2b:
    image: mongo:latest
    restart: always
    command: mongod --shardsvr --replSet shard2rs --bind_ip_all --port 27017
    ports:
      - "27025:27017"
    volumes:
      - shard2b_data:/data/db
      - ./scripts:/scripts
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    depends_on:
      shard2a:
        condition: service_started

  shard2c:
    image: mongo:latest
    restart: always
    command: mongod --shardsvr --replSet shard2rs --bind_ip_all --port 27017
    ports:
      - "27026:27017"
    volumes:
      - shard2c_data:/data/db
      - ./scripts:/scripts
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    depends_on:
      shard2a:
        condition: service_started
      shard2b:
        condition: service_started

  # Инициализатор шарда 2
  shard2_init:
    image: mongo:latest
    volumes:
      - ./scripts:/scripts
    networks:
      - app-network
    entrypoint: [ "/bin/bash", "/scripts/wait-and-init-shard2.sh" ]
    depends_on:
      shard2a:
        condition: service_healthy
      shard2b:
        condition: service_healthy
      shard2c:
        condition: service_healthy

  # Маршрутизатор запросов (mongos)
  mongos_router:
    image: mongo:latest
    command:
      [
        "mongos",
        "--configdb",
        "configrs/configSrv1:27017,configSrv2:27017,configSrv3:27017",
        "--bind_ip_all",
        "--port",
        "27020"
      ]
    ports:
      - "27020:27020"
    volumes:
      - ./scripts:/scripts
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "27020", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 20s
      retries: 15
      start_period: 90s
    depends_on:
      cfg_init:
        condition: service_completed_successfully
      shard1_init:
        condition: service_completed_successfully
      shard2_init:
        condition: service_completed_successfully

  # Финальная инициализация кластера
  cluster_init:
    image: mongo:latest
    volumes:
      - ./scripts:/scripts
    networks:
      - app-network
    entrypoint: [ "/bin/bash", "/scripts/wait-and-init-cluster.sh" ]
    depends_on:
      mongos_router:
        condition: service_healthy
  # Redis Cluster ноды
  redis-node-1:
    image: "redis:8.4-alpine"
    container_name: redis-node-1
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    ports:
      - "6379"
    volumes:
      - redis_node_1_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  redis-node-2:
    image: "redis:8.4-alpine"
    container_name: redis-node-2
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    ports:
      - "6379"
    volumes:
      - redis_node_2_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  redis-node-3:
    image: "redis:8.4-alpine"
    container_name: redis-node-3
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    ports:
      - "6379"
    volumes:
      - redis_node_3_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  redis-node-4:
    image: "redis:8.4-alpine"
    container_name: redis-node-4
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    ports:
      - "6379"
    volumes:
      - redis_node_4_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  redis-node-5:
    image: "redis:8.4-alpine"
    container_name: redis-node-5
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    ports:
      - "6379"
    volumes:
      - redis_node_5_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  redis-node-6:
    image: "redis:8.4-alpine"
    container_name: redis-node-6
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    ports:
      - "6379"
    volumes:
      - redis_node_6_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  # Инициализатор Redis кластера
  redis-cluster-init:
    image: "redis:8.4-alpine"
    container_name: redis-cluster-init
    restart: "no"
    depends_on:
      redis-node-1:
        condition: service_healthy
      redis-node-2:
        condition: service_healthy
      redis-node-3:
        condition: service_healthy
      redis-node-4:
        condition: service_healthy
      redis-node-5:
        condition: service_healthy
      redis-node-6:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      - ./scripts:/scripts
    entrypoint: [ "/bin/sh", "/scripts/init-redis-cluster.sh" ]
volumes:
  configSrv1_data: { }
  configSrv1_config: { }
  configSrv2_data: { }
  configSrv2_config: { }
  configSrv3_data: { }
  configSrv3_config: { }
  shard1a_data: { }
  shard1b_data: { }
  shard1c_data: { }
  shard2a_data: { }
  shard2b_data: { }
  shard2c_data: { }
  redis_node_1_data: { }
  redis_node_2_data: { }
  redis_node_3_data: { }
  redis_node_4_data: { }
  redis_node_5_data: { }
  redis_node_6_data: { }

networks:
  app-network:
    driver: bridge