name: mongo-sharding

services:
  # ---------------- CONFIG SERVER ----------------
  configSrv:
    image: mongo:7
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - config-data:/data/db
    command: ["mongod","--configsvr","--replSet","config_server","--bind_ip_all","--port","27017"]
    healthcheck:
      test: ["CMD","mongosh","--port","27017","--quiet","--eval","db.adminCommand({ ping: 1 })"]
      interval: 5s
      start_period: 10s

  # ---------------- SHARD 1 ----------------
  shard1:
    image: mongo:7
    restart: always
    ports:
      - "27018:27018"
    volumes:
      - shard1-data:/data/db
    command: ["mongod","--shardsvr","--replSet","shard1","--bind_ip_all","--port","27018"]
    healthcheck:
      test: ["CMD","mongosh","--port","27018","--quiet","--eval","db.adminCommand({ ping: 1 })"]
      interval: 5s
      start_period: 10s

  # ---------------- SHARD 2 ----------------
  shard2:
    image: mongo:7
    restart: always
    ports:
      - "27019:27019"
    volumes:
      - shard2-data:/data/db
    command: ["mongod","--shardsvr","--replSet","shard2","--bind_ip_all","--port","27019"]
    healthcheck:
      test: ["CMD","mongosh","--port","27019","--quiet","--eval","db.adminCommand({ ping: 1 })"]
      interval: 5s
      start_period: 10s

  # ---------------- MONGOS ROUTER ----------------
  mongos_router:
    image: mongo:7
    restart: always
    ports:
      - "27020:27020"
    command: ["mongos","--configdb","config_server/configSrv:27017","--bind_ip_all","--port","27020"]
    depends_on:
      - configSrv
      - shard1
      - shard2
    healthcheck:
      test: ["CMD","mongosh","--port","27020","--quiet","--eval","db.adminCommand({ ping: 1 })"]
      interval: 5s
      start_period: 10s

  # ---------------- API APP ----------------
  api_app:
    build:
      context: ./api_app
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mongos_router
    environment:
      MONGODB_URL: "mongodb://mongos_router:27020/"
      MONGODB_DATABASE_NAME: "somedb"
      # REDIS_URL пока не нужен
    ports:
      - "8080:8080"

volumes:
  config-data:
  shard1-data:
  shard2-data:
