name: mongo-sharding-repl

services:
  pymongo_api:
    container_name: pymongo_api
    build:
      context: api_app
      dockerfile: Dockerfile
    depends_on:
      mongos_router:
        condition: service_healthy
    ports:
      - 8080:8080
    environment:
      MONGODB_URL: "mongodb://mongos_router:27020"
      MONGODB_DATABASE_NAME: "somedb"
    networks:
      - app-network

  # Серверы конфигурации (3 реплики)
  configSrv1:
    image: mongo:latest
    container_name: configSrv1
    restart: always
    networks:
      - app-network
    volumes:
      - config1-data:/data/db
      - ./scripts:/scripts
    command:
      [
        "--configsvr",
        "--replSet",
        "config_server",
        "--bind_ip_all",
        "--port",
        "27017"
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "27017", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 30s
      timeout: 5s
      retries: 3

  configSrv2:
    image: mongo:latest
    container_name: configSrv2
    restart: always
    networks:
      - app-network
    volumes:
      - config2-data:/data/db
      - ./scripts:/scripts
    command:
      [
        "--configsvr",
        "--replSet",
        "config_server",
        "--bind_ip_all",
        "--port",
        "27017"
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "27017", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 30s
      timeout: 5s
      retries: 3

  configSrv3:
    image: mongo:latest
    container_name: configSrv3
    restart: always
    networks:
      - app-network
    volumes:
      - config3-data:/data/db
      - ./scripts:/scripts
    command:
      [
        "--configsvr",
        "--replSet",
        "config_server",
        "--bind_ip_all",
        "--port",
        "27017"
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "27017", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 30s
      timeout: 5s
      retries: 3

  # 1-й шард (3 реплики)
  shard1a:
    image: mongo:latest
    container_name: shard1a
    restart: always
    networks:
      - app-network
    volumes:
      - shard1a-data:/data/db
      - ./scripts:/scripts
    command:
      [
        "--shardsvr",
        "--replSet",
        "shard1",
        "--bind_ip_all",
        "--port",
        "27018"
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "27018", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 30s
      timeout: 5s
      retries: 3

  shard1b:
    image: mongo:latest
    container_name: shard1b
    restart: always
    networks:
      - app-network
    volumes:
      - shard1b-data:/data/db
      - ./scripts:/scripts
    command:
      [
        "--shardsvr",
        "--replSet",
        "shard1",
        "--bind_ip_all",
        "--port",
        "27018"
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "27018", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 30s
      timeout: 5s
      retries: 3

  shard1c:
    image: mongo:latest
    container_name: shard1c
    restart: always
    networks:
      - app-network
    volumes:
      - shard1c-data:/data/db
      - ./scripts:/scripts
    command:
      [
        "--shardsvr",
        "--replSet",
        "shard1",
        "--bind_ip_all",
        "--port",
        "27018"
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "27018", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 30s
      timeout: 5s
      retries: 3

  # 2-й шард (3 реплики)
  shard2a:
    image: mongo:latest
    container_name: shard2a
    restart: always
    networks:
      - app-network
    volumes:
      - shard2a-data:/data/db
      - ./scripts:/scripts
    command:
      [
        "--shardsvr",
        "--replSet",
        "shard2",
        "--bind_ip_all",
        "--port",
        "27019"
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "27019", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 30s
      timeout: 5s
      retries: 3

  shard2b:
    image: mongo:latest
    container_name: shard2b
    restart: always
    networks:
      - app-network
    volumes:
      - shard2b-data:/data/db
      - ./scripts:/scripts
    command:
      [
        "--shardsvr",
        "--replSet",
        "shard2",
        "--bind_ip_all",
        "--port",
        "27019"
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "27019", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 30s
      timeout: 5s
      retries: 3

  shard2c:
    image: mongo:latest
    container_name: shard2c
    restart: always
    networks:
      - app-network
    volumes:
      - shard2c-data:/data/db
      - ./scripts:/scripts
    command:
      [
        "--shardsvr",
        "--replSet",
        "shard2",
        "--bind_ip_all",
        "--port",
        "27019"
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "27019", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 30s
      timeout: 5s
      retries: 3

  # Инициализатор
  init_mongo:
    image: mongo:latest
    container_name: init_mongo
    restart: "no"
    depends_on:
      configSrv1:
        condition: service_healthy
      configSrv2:
        condition: service_healthy
      configSrv3:
        condition: service_healthy
      shard1a:
        condition: service_healthy
      shard1b:
        condition: service_healthy
      shard1c:
        condition: service_healthy
      shard2a:
        condition: service_healthy
      shard2b:
        condition: service_healthy
      shard2c:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      - ./scripts:/scripts
    entrypoint: [ "/bin/bash", "/scripts/init-replica-sets.sh" ]

  #роутер
  mongos_router:
    image: mongo:latest
    container_name: mongos_router
    restart: always
    ports:
      - "27020:27020"
    depends_on:
      init_mongo:
        condition: service_completed_successfully
    networks:
      - app-network
    volumes:
      - ./scripts:/scripts
    command:
      [
        "mongos",
        "--configdb",
        "config_server/configSrv1:27017,configSrv2:27017,configSrv3:27017",
        "--bind_ip_all",
        "--port",
        "27020"
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "27020", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 30s
      timeout: 5s
      retries: 3

networks:
  app-network:
    driver: bridge

volumes:
  config1-data:
  config2-data:
  config3-data:
  shard1a-data:
  shard1b-data:
  shard1c-data:
  shard2a-data:
  shard2b-data:
  shard2c-data: